version: '3.8'

services:
  run-model-locally:
    container_name: emotion_model-local-starter
    restart: "no"
    image: tianon/true
    depends_on:
      - emotion-model

  emotion-model:
    container_name: emotion_model
    build:
      context: .
    command: poetry run python ./emotion_model/model.py --name emotion_model  --type emotion
    image: emotion-model:latest
    restart: unless-stopped
    volumes:
      - .:/app-workspace
    env_file:
      - .env
    networks:
      - picachu-api-private_picachu-net

networks:
  picachu-api-private_picachu-net:
    external: true