name: test emotion model

on:
  push:
    branches:
      - feature/#85zrv2enc-add-dvc-pipeline

jobs:
  test-and-report:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: iterative/setup-cml@v1

      - uses: iterative/setup-dvc@v1
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.9'

      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.2.2'

      - name: cml
        # env:
          # repo_token: ${{ secrets.GITHUB_TOKEN }}
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          poetry install
          dvc repro
          # Use DVC metrics diff to compare metrics to master
          git fetch --prune --unshallow
          dvc metrics diff --show-md master >> report.md
          # Add figure to report
          dvc plots diff --target loss.csv --show-vega master > vega.json
          vl2png vega.json -s 1.3 > vega.png
          echo '![](./vega.png)' >> report.md
          cml comment create --pr --publish report.md
